[package]
name = "andromeda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
atomic_enum = "0.2.0"
derivative = "2.2.0"
egui = "0.21.0"
egui-winit-ash-integration = { git = "https://github.com/NotAPenguin0/egui-winit-ash-integration" }
futures = "0.3.26"
log = { version = "0.4.17", features = ["std"] }
phobos = { git = "https://github.com/NotAPenguin0/phobos-rs" }
pretty_env_logger = "0.4.0"
raw-window-handle = "0.5.0"
tiny-tokio-actor = "0.3.3"
tokio = { version = "1.25.0", features = ["full"] }
winit = "0.28.1"
