[package]
name = "andromeda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-rt = "2.8.0"
anyhow = "1.0.69"
futures = "0.3.26"
phobos = "0.3.2"
winit = "0.28.1"
