[package]
name = "input"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
util = { path = "../util" }
winit = "0.28.3"
derivative = "2.2.0"
log = "0.4.17"
scheduler = { path = "../scheduler" }
inject = { path = "../inject" }